# Generated by Django 4.2.7 on 2023-12-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanShoeApp', '0009_alter_sellerorders_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
