# Generated by Django 4.2.7 on 2023-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanShoeApp', '0010_delete_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
    ]
