# Generated by Django 4.2.7 on 2023-12-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanShoeApp', '0011_carouselitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
